// Types file so it's easier to spot errors

// Handling pagination
export const SET_PAGINATION = 'SET_PAGINATION';

// Handling user data
export const STORE_USER_TOKEN = 'STORE_USER_TOKEN';
export const STORE_USER_IDENTITY = 'STORE_USER_IDENTITY';
export const UPDATE_CURRENT_PAGE_SAVES = 'UPDATE_CURRENT_PAGE_SAVES';
export const APPEND_USER_SAVES = 'APPEND_USER_SAVES';
export const DISPLAY_THREADS_AND_COMMENTS = 'DISPLAY_THREADS_AND_COMMENTS';
export const DISPLAY_ONLY_THREADS = 'DISPLAY_ONLY_THREADS';
export const DISPLAY_ONLY_COMMENTS = 'DISPLAY_ONLY_COMMENTS';
export const STORE_USER_SEARCH = 'STORE_USER_SEARCH';
export const STORE_SAVES_ALPHABETICAL = 'STORE_SAVES_ALPHABETICAL';
export const STORE_SAVES_CHRONOLOGICAL = 'STORE_SAVE_VALUES_WITH_CHRONOLOGICALLY';